# Generated by Django 5.2 on 2025-04-28 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenarticle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
