# Generated by Django 3.1.12 on 2025-04-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='banners.banner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='current_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_banner_image', to='banners.bannerimage'),
        ),
    ]
