# Generated by Django 5.2 on 2025-06-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_writtenarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='writtenarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='written_articles', to='banners.tag'),
        ),
        migrations.AddField(
            model_name='bannertitle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_titles', to='banners.language'),
        ),
        migrations.AddField(
            model_name='writtenarticle',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='banners.language'),
        ),
    ]
