# Generated by Django 3.1.12 on 2025-04-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20250416_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='content_url',
            field=models.URLField(default='http://default-url.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='s', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='article',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
