# Generated by Django 3.1.12 on 2025-04-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20250416_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='current_image',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.banner'),
        ),
    ]
