# Generated by Django 3.1.12 on 2025-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20250416_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='banners.Tag'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='banners', to='banners.Tag'),
        ),
    ]
