# Generated by Django 3.1.12 on 2025-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20250416_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='random_tag_probability',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tags', models.ManyToManyField(related_name='verticals', to='banners.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='verticals',
            field=models.ManyToManyField(blank=True, related_name='articles', to='banners.Vertical'),
        ),
        migrations.AddField(
            model_name='banner',
            name='verticals',
            field=models.ManyToManyField(blank=True, related_name='banners', to='banners.Vertical'),
        ),
    ]
