# Generated by Django 3.1.12 on 2025-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_auto_20250416_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
