# Generated by Django 3.1.12 on 2025-04-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_auto_20250425_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BannerTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('clicks', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='banners.banner')),
            ],
        ),
    ]
