site_name: BannerProject Docs
repo_url: https://github.com/MishaNyKarl/banner_project
nav:
  - Главная: index.md
  - Установка: setup.md
  - Деплой local: deployment_local.md
  - Деплой server: deployment_server.md
plugins:
  - search
  - mkdocstrings
theme:
  name: material
