name: CI/CD

on:
  push:
    branches:
      - master         # или ваша ветка развёртывания

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Django tests
        working-directory: ./banner_project
        run: python manage.py test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/srv/publicationinfo/banner_project/"
          strip_components: 1
          overwrite: true
          debug: true

      - name: Run deployment commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /srv/publicationinfo/banner_project/
            
            if [ ! -d venv ]; then
              python3 -m venv venv
            fi
            
            source venv/bin/activate
            git reset --hard HEAD
            pip install -r requirements.txt
            python3 banner_project/manage.py migrate --noinput
            python3 banner_project/manage.py collectstatic --noinput
            sudo systemctl restart banner_project
            sudo systemctl reload nginx
